spring.application.name=explore

# use wild card to expose all end points
# can expose individual end points with a comma-delimited list
management.endpoints.web.exposure.include=health,info

management.info.env.enabled=true

info.app.name=pikachu
info.app.description=does pika pika chu
info.app.version=9.11